"""phase7_customer_profile_tenant_unique

Revision ID: 5358598b51f3
Revises: dad40f1dcf9f
Create Date: 2026-08-09 05:31:32.103610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5358598b51f3'
down_revision: Union[str, None] = 'dad40f1dcf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_profiles_user_id_key', 'customer_profiles', type_='unique')
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_customer_profiles_tenant_user', 'customer_profiles', ['tenant_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_profiles_tenant_user', 'customer_profiles', type_='unique')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.create_unique_constraint('customer_profiles_user_id_key', 'customer_profiles', ['user_id'])
    # ### end Alembic commands ###
