"""Canonical ledger account codes."""

from __future__ import annotations

from enum import StrEnum


class LedgerAccount(StrEnum):
    PLATFORM_CASH = "PLATFORM_CASH"
    CUSTOMER_RECEIVABLE = "CUSTOMER_RECEIVABLE"
    TAX_LIABILITY = "TAX_LIABILITY"
    PLATFORM_FEE_REVENUE = "PLATFORM_FEE_REVENUE"
    PLATFORM_COMMISSION = "PLATFORM_COMMISSION"
    MERCHANT_PAYABLE = "MERCHANT_PAYABLE"
    RIDER_PAYABLE = "RIDER_PAYABLE"
    PLATFORM_CLEARING = "PLATFORM_CLEARING"


class LedgerDirection(StrEnum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class LedgerEventType(StrEnum):
    ORDER_PAYMENT_CAPTURED = "ORDER_PAYMENT_CAPTURED"
    PAYMENT_REFUND = "PAYMENT_REFUND"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
